### ISSUE TITLE
Search Bar > Keyboard shortcut

### ISSUE THREAD

**Issue by Victa** [gitscout/gitscout-feedback#10]
What about adding a keyboard shortcut for the search? Would be great to have `CMD + F`!

**Comment by jeremybenaim** [comment]
Right! Thanks a bunch for this one! :)

**Comment by michael-lefebvre** [comment]
done ✌️ available  in next release

**Comment by jeremybenaim** [comment]
Fixed in the 0.3.4  🎉 

To update, simply re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now"

Thanks :)
