### ISSUE TITLE
Cannot Unassign Myself from Issue

### ISSUE THREAD

**Issue by Elidrake** [gitscout/gitscout-feedback#100]
It seems to be that, for whatever reason, the issue will show my username as lowercase (i.e. @elidrake), but the application sees my name as capitalized (i.e. @Elidrake).  Not entirely certain as to why.  Also, this allows me to assign myself twice from within the interface.

**Comment by michael-lefebvre** [comment]
Hi @Elidrake, fixed in [0.5.8](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#058---212017), thanks for reporting this 🙏
