### ISSUE TITLE
Launch at login not working

### ISSUE THREAD

**Issue by IanMartinGroup** [gitscout/gitscout-feedback#101]
Even after disabling it in preferences, it still launches at login, everytime.

**Comment by areskub** [comment]
What version are you on?

**Comment by michael-lefebvre** [comment]
@IanMartinGroup thanks for report, fix will be available in next release

**Comment by greystate** [comment]
This is so annoying :-)

(Version 0.5.7 for me)

**Comment by michael-lefebvre** [comment]
Hi @greystate, patch will be released this week 🙂

**Comment by michael-lefebvre** [comment]
@IanMartinGroup and @greystate, fixed in [0.5.8](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#058---212017) 😀
