### ISSUE TITLE
Inline code not styled with a monospaced font

### ISSUE THREAD

**Issue by maxvoltar** [gitscout/gitscout-feedback#102]
![image](https://cloud.githubusercontent.com/assets/125779/21408309/38455760-c789-11e6-8cef-39598be521d9.png)

**Comment by areskub** [comment]
good call

**Comment by michael-lefebvre** [comment]
fixed in [0.5.8](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#058---212017)
