### ISSUE TITLE
Unexpected CMD + click behavior on links

### ISSUE THREAD

**Issue by maxvoltar** [gitscout/gitscout-feedback#103]
When clicking a link while holding `CMD`, the expected behavior is for the link to open in a browser window behind the app you're currently working in (allows you to open multiple links in the background while not losing focus).

In GS, it opens the link in a browser window in front of the app, *and* opens it in some weird mini-window (never seen this before).

**Comment by areskub** [comment]
Seems like the same issue as #11 to me @michael-lefebvre

**Comment by michael-lefebvre** [comment]
fixed in [0.5.8](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#058---212017)
