### ISSUE TITLE
[Feature Request] Drag and drop sorting of repositories under an organization

### ISSUE THREAD

**Issue by joshparolin** [gitscout/gitscout-feedback#105]
As a user I want to drag and drop my repositories under an organization to view them in an order that aligns with how I prioritize them.

**Comment by michael-lefebvre** [comment]
@joshparolin feature available in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂 You can reorder your Organizations from your settings. Soon you will be able to reorder repositories too.

**Comment by allthesignals** [comment]
Hi! I love this tool. I don't think v0.6.2 gets at what this issue is, however, which is to reorder Repositories under an organization. Should we reopen? I would find this to be very useful! It sounds like it's "soon" - thoughts? @michael-lefebvre
