### ISSUE TITLE
gitscout doesn't close when the computer is trying to shut down

### ISSUE THREAD

**Issue by agisilaos** [gitscout/gitscout-feedback#109]
gitscout doesn't close when the computer is trying to shut down. Also I can't close gitscout from the menu that I screenshot above. 

[Screen Shot 2017-01-03 at 18.57.11](http://static.gitscout.com/180295f3b172086f1ef589f015420b8bd7de3611e92baf0b4d511f1a157ad1fd.png)

**Comment by Adrien-Griveau** [comment]
@agisilaos Thanks for these feedback. We will try our best to solve this issue in the next release.

**Comment by agisilaos** [comment]
@Adrien-Griveau Glad that I could help. I really love the app and Iike to find this kind of bugs and report them.

**Comment by Adrien-Griveau** [comment]
@agisilaos thank you very much for your help for those kind words. 👍

**Comment by michael-lefebvre** [comment]
@agisilaos fixed in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂

**Comment by agisilaos** [comment]
Nice @michael-lefebvre. Will update it 👍
