### ISSUE TITLE
Bug > Left Click + CMD key on an issue opens a new window

### ISSUE THREAD

**Issue by Victa** [gitscout/gitscout-feedback#11]
I noticed that clicking on an issue in the list + the `CMD` key (or the `SHIFT` key) opens a new Gitscout window.

**Comment by jeremybenaim** [comment]
Yea, thats more Gitscout for free! \o/

jk, gonna fix it soon :)

**Comment by jeremybenaim** [comment]
Hey @Victa, hope you're doing well! Latest version resolves this issue! :)

**Comment by antoinerey** [comment]
It seems that it's still there for me.

Clicking while holding [SHIFT | ALT | CMD] opens a new empty window. This window never loads, it's still blank after a minute or so.

I'm using Gitscout 0.5.4.

**Comment by areskub** [comment]
Maybe @michael-lefebvre should investigate. Thanks for the report!

**Comment by michael-lefebvre** [comment]
fixed in [0.5.8](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#058---212017)
