### ISSUE TITLE
Label dropdown contains stale data from github.

### ISSUE THREAD

**Issue by pkrawc** [gitscout/gitscout-feedback#110]
When selecting labels in Gitscout to tag an issue I'm seeing all of the labels ever created for a repo even though I've reorganized and deleted a number of them.

**Comment by jeremybenaim** [comment]
Thanks for reporting this @pkrawc. Working on it!

**Comment by michael-lefebvre** [comment]
@pkrawc, I saw and fixed this 2 days ago. I was hoping no one sees it before I shipped the patch, I lost 😁. It will be available in the next release. Thanks

**Comment by pkrawc** [comment]
@michael-lefebvre Thanks for the quick work! :wink:

**Comment by michael-lefebvre** [comment]
@pkrawc fixed in [v0.6.0](https://github.com/gitscout/gitscout-feedback/issues/122) 😀
