### ISSUE TITLE
Start Button is missing in app

### ISSUE THREAD

**Issue by justinsalsburey** [gitscout/gitscout-feedback#111]
Start button should be visible above date if dates are shown or centered vertically if not. 

Currently the start button seems to be missing in all scenarios.

**Comment by Adrien-Griveau** [comment]
@justinsalsburey What do you mean by start button? Can you provide us a screenshot?

**Comment by justinsalsburey** [comment]
Hah! @Adrien-Griveau I left this in the wrong repository because gitscout was automatically added. Disregard

**Comment by Adrien-Griveau** [comment]
@justinsalsburey 😉 no problem. Hope you have fun using Gitscout.

Closing this issue.
