### ISSUE TITLE
Ability to self-update application

### ISSUE THREAD

**Issue by NeckBeardPrince** [gitscout/gitscout-feedback#112]
Since the Gitscout website does not list the latest released version you have no way of knowing what the latest is, unless you come here and look at the CHANGELOG. Be nice if Gitscout checked for updates.

**Comment by Adrien-Griveau** [comment]
@NeckBeardPrince This a good point. We are working on a changelog channel that will appear in in the app. 

Thanks for your feedbacks. 🖖

**Comment by michael-lefebvre** [comment]
@NeckBeardPrince feature available in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂

**Comment by NeckBeardPrince** [comment]
Awesome! Great work!
