### ISSUE TITLE
Typo in "lost connection" alert

### ISSUE THREAD

**Issue by evaneykelen** [gitscout/gitscout-feedback#114]
<img width="479" alt="gitscout typo" src="https://cloud.githubusercontent.com/assets/11846/21732093/0f2d6a76-d458-11e6-9ba1-8b80ccca5003.png">

`Oups` is usually spelled as `Oops`. 

Oups looks more posh though, a bit French, so feel free to ignore my nitpicking :-)

**Comment by areskub** [comment]
Oups is indubitably French. 😊
