### ISSUE TITLE
Misspellings

### ISSUE THREAD

**Issue by Charlotteis** [gitscout/gitscout-feedback#115]
In sign up: 
- "optionnal" should read "optional"
- "confirm your informations" should probably read "confirm your information"

In notifications:
- "here come the troubles!" should be "here comes trouble!"

In app start for the first time:
- "Follow the Gitscout feedbacks repositoty" should be "Follow the Gitscout feedbacks repository"

Thanks for the app, looks cool! :D

**Comment by jeremybenaim** [comment]
Thanks @Charlotteis ! The good news is that our Javascript is better than our English 😅

**Comment by areskub** [comment]
Corrected all of those. Merge pending. Thanks @Charlotteis

**Comment by michael-lefebvre** [comment]
@Charlotteis fixed in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 
We opened a [new repository](https://github.com/gitscout/i18n) with our texts files. Feel free to submit your corrections. Thanks again for your feedback 🙂

**Comment by Charlotteis** [comment]
@michael-lefebvre ah very cool! I shall!
