### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by varjmes** [gitscout/gitscout-feedback#116]
As I can't see the source code (I wanted to PR some fixes for you), does that mean that Git Scout will be a paid for model at some point?

EDIT: On second thought it was probably wrong to assume this, and maybe you just dont want to share the code right now for many good reasons :)

**Comment by jeremybenaim** [comment]
@Charlotteis no worries, that's definitely a legit (and really good) question 🙂 

We haven't deicide on anything yet but adding some paying options in the future is something we have mind, yes.

To be honest, Gitscout costs us money every month and represents a lot of hours of work but we figured that keeping it free and just asking for feedback in return would be just good enough for us, and we're actually more than happy with that 😊

That being said, we definitely want to bring this project one step further and it will require a more robust infrastructure and involve extra costs.
