### ISSUE TITLE
Relative dates are ambiguous

### ISSUE THREAD

**Issue by Victa** [gitscout/gitscout-feedback#12]
Just sharing my opinion. Feel free to take it or not.

I feel like relative dates are great when the message was posted a few minutes (or hours) ago but becomes ambiguous when the comment was posted a few weeks/months ago.

![Screen Shot 2016-07-13 at 17.57.53](http://static.gitscout.com/f29496da8d2d4dd97e39d2a48e1fd7b3e02e25b7cae21ea9630a4da79d1174cb.png)

`7 months ago` is not very precise. I would prefer to have an absolute date 

I like what Gmail does (they mix both relative and absolute).

![Screen Shot 2016-07-13 at 18.02.57](http://static.gitscout.com/1c8ed1d70a00ba6c00ca289f653e873301ae1c225269bb0c69c23535bf4f03b3.png)

On Twitter; I think dates are relative only when they are less than a few days.

**Comment by jeremybenaim** [comment]
Hey @victa, thanks for the feedback :) 
What do you think about a tooltip on hover w/ the absolute date ?

**Comment by Victa** [comment]
Yup! that would be great :+1:

**Comment by areskub** [comment]
Relative dates are the worst. Maybe we should have a rule where we use rel dates for like the first week and then use real dates?

**Comment by jeremybenaim** [comment]
Sounds good to me, yet, keeping a tooltip w/ absolute date for the first week

**Comment by areskub** [comment]
yes

**Comment by jeremybenaim** [comment]
Ambiguous dates are no more! :metal: 

We just released a new version, to grab it please re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now"

Cheers :)
