### ISSUE TITLE
OAuth Permissions - Security Concerns

### ISSUE THREAD

**Issue by elzii** [gitscout/gitscout-feedback#124]
Hey there,

Why does GitScout need write access to my public/private repositories? 

![image](https://cloud.githubusercontent.com/assets/1827950/21946436/5e0674b6-d995-11e6-8262-b16c1c07d468.png)

Cheers

**Comment by ncouraud** [comment]
IIRC This is a consequence of repo-scope auth permissions. There is a public_repo scope, but then those folks with private repos wouldn't be able to access their issues. https://developer.github.com/v3/oauth/#scopes

Realistically, GH doesn't separate issues and code in their permission scopes. It's either all or nothing

**Comment by jeremybenaim** [comment]
@elzii as @ncouraud pointed out there's no way for us to ask the permission only for the issues so we have to ask you for a full-access 😕

That being said we never access your code and don't store any sensitive information (see https://gitscout.com/privacy for more details about this)

Hopefully GitHub will offer a better granularity in the scopes available some day.

**Comment by elzii** [comment]
@jeremybenaim Thank you for taking the time to respond - I understand. Hopefully Github changes that - I think that will be an important for you guys towards getting organization accounts to use Gitscout comfortably.
