### ISSUE TITLE
Spelling and grammar errors in onboarding flow

### ISSUE THREAD

**Issue by sentience** [gitscout/gitscout-feedback#125]
The user details prompt is entitled “Confirm your informations”, which is grammatically incorrect. “Confirm your information” would be correct, and “Confirm your details” would probably be more clear to most users.

![Gitscout](http://static.gitscout.com/dd26dead59d1bcb7d8e01ebc067e88f7a53382f94e1f7a8011b4bdb9b4b8ac2d.png)

Then there is a prompt to follow the Gitscout feedback repository, which likewise is inappropriately pluralised “Gitscout feedbacks repository”. Also, “repository” is misspelled “repositoty”.

![Gitscout](http://static.gitscout.com/1d3cbfbade03a5b41a61b6e780fc6ffcde2f7773105277d239e5cbe293f8d291.png)

**Comment by michael-lefebvre** [comment]
we definitely need to improve our texts validation workflow 😓
Thank you @sentience 🙂
