### ISSUE TITLE
Prevents computer from restarting

### ISSUE THREAD

**Issue by pixeline** [gitscout/gitscout-feedback#127]
I needed to reboot my computer. Apple Menu > Reboot... 

Among the dozen applications that were open, two prevented the shutdown, among which, gitscout. Would it be possible to make it accept the shutdown ? Let me know if you need more info.

Thank you!
a.

**Comment by michael-lefebvre** [comment]
I will investigate, I think the problem was introduced with #75 fix. Thanks for your feedback.

**Comment by SamuAlfageme** [comment]
I was about to report this same thing that has been bugging me for a few days now, yeah.

The program is unresponsive to "Quit" option from the dock menu nor the system trying to shut it down, so it prevents the system from halting every time you retry. Until you open the window and use the Quit on the menubar or ⌘Q option.

**Comment by michael-lefebvre** [comment]
@pixeline and @SamuAlfageme, bug fixed in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂

**Comment by pixeline** [comment]
Awesome, thank you!
