### ISSUE TITLE
Issues List > Dates

### ISSUE THREAD

**Issue by Victa** [gitscout/gitscout-feedback#13]
I think that would make more sense to show the date of the latest comment (also because you put the date in blue when the issue is updated) instead of showing the date of the first comment of the issue.

![Screen Shot 2016-07-13 at 18.05.07](http://static.gitscout.com/b90c0e7813a49ade96cebbf7beb875d3df106e70f2f9048c6d41fd2558a2bb80.png)

Side note: That would be nice to have a blue dot next to the title in the list instead (or in addition) to the blue date when the issue is updated).

**Comment by jeremybenaim** [comment]
fixed in the 0.3.4 ;)

To update, re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now"
