### ISSUE TITLE
Can't quit from dock

### ISSUE THREAD

**Issue by chrismccoy** [gitscout/gitscout-feedback#134]
Unlike all other apps, you cannot right click and quit the app from the dock, you have to open the app and use the menu quit item.

not sure if this was left out on purpose or not, other than that love the app, was using cashew (29.99) but switched to gitscout.

keep up the good work

**Comment by jeremybenaim** [comment]
@chrismccoy we're currently fixing this bug! It should be resolved in the next version. Thanks!

**Comment by michael-lefebvre** [comment]
@chrismccoy fixed in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂
