### ISSUE TITLE
beautiful application.. Github enterprise support?

### ISSUE THREAD

**Issue by tru64ufs** [gitscout/gitscout-feedback#135]
one great application...
but we definitely need on-premise Github enterprise support ...
thank u

**Comment by jeremybenaim** [comment]
@tru64ufs closing this one as it's a duplicate of #58. But to sum up there's two thing about an Enterprise integration: Login w/ an GH Enterprise account (this should be available soon) and an on-premise version of Gitscout, which is in our minds but not before a few weeks/months
