### ISSUE TITLE
Bad English

### ISSUE THREAD

**Issue by jpike88** [gitscout/gitscout-feedback#136]
If you're going to write stuff in English, you need a proof reader.

'It help you to manage and plan your daily work with smarts features across all your work station'

This looks very bad. Also:

'Confirm your informations'

This also looks bad.

Please get someone who has decent English to look at everything

**Comment by Adrien-Griveau** [comment]
@jpike88 Thanks for you feedbacks. What do you think about this?

> "Gitscout is more than an issues viewer. It help you to manage and plan your daily work with smarts features across all your work stations. Don't worry, your data will always be in a safe place."
"Gitscout doesn’t only help you stay on top of your issues. We help you manage and plan your workload with smart features. Don’t worry, your data will always be in a safe place." (edited)


> "Confirm your informations”
“Confirm your information"

**Comment by jpike88** [comment]
Yeah that's better
