### ISSUE TITLE
New issues don't appear in the list

### ISSUE THREAD

**Issue by antoinerey** [gitscout/gitscout-feedback#137]
When creating a new issue, it does not automatically appear in the list. I have to select another repository, and come back to the one I'm interested in to get the issue on the list.

**Step to reproduce**

1. Select a repository
1. Create a new issue within this repository
1. Validate (The modal is closed, and you are redirected to the list of issues)
1. **The issue is not on the list**

Edit: Mmmh, this issue show up right after the validation. So maybe that's not always occuring ?

**Comment by michael-lefebvre** [comment]
@antoinerey, does it happen when the selected repository is filtered with a search? I think I just fixed this but it will help me if you can confirm me your context.

you can use [the Playground](https://github.com/gitscout/playground) to make tests.

thanks

**Comment by antoinerey** [comment]
Yes it seems so. I tried with `Open issues` and `Recent ones`, the issues do not appear. However, when the search bar is empty, they are correctly added to the list.

**Comment by michael-lefebvre** [comment]
Great! The fix will be available in next version 😁

**Comment by michael-lefebvre** [comment]
Fixed in [v0.6.4](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#064---422017)).

**Comment by antoinerey** [comment]
@michael-lefebvre Since 0.6.4, creating an issue removes every filter from the search bar. Indeed, the new issue appears in the list, but I think that keeping my filters as before is important too.
