### ISSUE TITLE
Add some message after clicking on download

### ISSUE THREAD

**Issue by antoinerey** [gitscout/gitscout-feedback#141]
When there is an update available, a popup shows up asking if we want to download it or not. When clicking on *download*, nothing happens (from the user point of view). The download starts in background, but nothing changed in the interface.

I thought the download button wasn't working.

I think that just a simple message confirming the action could be very helpful.

EDIT: I can't post any screenshot, I just downloaded the new release 😆

**Comment by michael-lefebvre** [comment]
we fixed this in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140), Gitscout self-upgrades in the background now. You will be only prompt to restart when download is finish.

**Comment by antoinerey** [comment]
@michael-lefebvre Oh, perfect ! I didn't read the full changelog 😇
