### ISSUE TITLE
Dock badge is not updated

### ISSUE THREAD

**Issue by rno** [gitscout/gitscout-feedback#142]
![Screenshot 2017-01-25 11.43.28](http://static.gitscout.com/f3dad7fc7a5568f0567049d939de2cab451beb3656d2c69e2825ea392f57880f.png)

I read all the notifications I had and the badge is still showing `2`

**Comment by michael-lefebvre** [comment]
did you use the "mark as read" swipe/button, or walk through all notifications, or both?

**Comment by rno** [comment]
@michael-lefebvre I walked through them I think. I'll double check just to be sure once I get notifications again.

**Comment by michael-lefebvre** [comment]
@rno I think we fixed this, do you confirm?
