### ISSUE TITLE
Unable to follow issue links

### ISSUE THREAD

**Issue by antoinerey** [gitscout/gitscout-feedback#144]
Clicking on issue links (eg. #86) closes the current issue, quickly opens the second one, and immediatly closes it.

**Steps to reproduce**
1. Click on any issue link (eg. #86)

**Informations**
1. MacOS Sierra 10.12.2
1. GitScout 0.6.2

Edit: Sometimes, it works as expected, the issue is correctly displayed.

**Comment by michael-lefebvre** [comment]
yes, I can reproduce it only with a active search, I will fixe this asap

**Comment by michael-lefebvre** [comment]
Hi @antoinerey, we just published a new release ([v0.6.4](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#064---422017)) which fix this issue. Can you confirm me this is ok for you?
