### ISSUE TITLE
Syncing notifications for five days now

### ISSUE THREAD

**Issue by nijikokun** [gitscout/gitscout-feedback#145]
I've had the following screen on Participating page for five days now with to no avail.

![https://i.imgur.com/21ykH7M.png](https://i.imgur.com/21ykH7M.png)

**Comment by michael-lefebvre** [comment]
Hello @nijikokun, we just published a [new release](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#064---422017) which includes an error log. 
Can you update the application and tell me if you get a message, please?

**Comment by nijikokun** [comment]
This works now :tada:

Thanks very much 💪
