### ISSUE TITLE
Small grammar issue

### ISSUE THREAD

**Issue by antoinerey** [gitscout/gitscout-feedback#148]
If there is only one assigne, shouldn't be `amouillard assigned himself 13 days ago` ?

![Capture d’écran 2017-02-01 à 11.22.13](http://static.gitscout.com/6847578e96fb7bb47a8c4c01c9e0449752eb889aa3fd43b5fb34e90a63be5e7d.png)

**Comment by areskub** [comment]
Not really since it can either be a "he" or a "she". So we stay gender neutral with "them".

**Comment by michael-lefebvre** [comment]
We chose this term as a gender-neutral language.

![pasted image at 2017_01_20 05_20 pm](https://cloud.githubusercontent.com/assets/279053/22503432/01a3fa68-e872-11e6-9b15-1f683323159f.png)

**Comment by antoinerey** [comment]
@areskub Oh. Thank you for the enlightenment, didn't think far enough :D

**Comment by Adrien-Griveau** [comment]
@antoinerey Thanks a lot for you many feedbacks that's help us a lot. cheers, 👍

**Comment by antoinerey** [comment]
@Adrien-Griveau You're welcome, such a pleasure to use GitScout everyday. That's my humble contibutions 😁
