### ISSUE TITLE
Add a way to format text with keyboard shortcuts

### ISSUE THREAD

**Issue by antoinerey** [gitscout/gitscout-feedback#150]
For exemple :

`CMD+B` for **bold**
`CMD+I` for *italic*

Github allows us to do this, and I find this quite useful. 😇

**Comment by michael-lefebvre** [comment]
We are working on a new version of the composer and enhance the editor's functionalities is on the todo list 🛠 🙂

**Comment by antoinerey** [comment]
@michael-lefebvre Can't wait to use this new version 😄

**Comment by michael-lefebvre** [comment]
Hi @antoinerey, you can now enjoy the new composer in [version 1.0.0-rc.1](https://github.com/gitscout/gitscout-feedback/issues/193) 😉
