### ISSUE TITLE
Github projects support

### ISSUE THREAD

**Issue by shinzui** [gitscout/gitscout-feedback#152]
It would be amazing if gitscout supported github projects. We heavily use projects to organize issues inside a repo, and across repos (on the organization level). I have to still go to github to place the issue in the correct column in a project, so it's easier to create issues from github. I would love to only use gitscout.

**Comment by onbjerg** [comment]
Duplicate of #61? 😊

**Comment by jeremybenaim** [comment]
Closing because of duplicate, yes ☺️
