### ISSUE TITLE
Disable notifications for hidden repositories?

### ISSUE THREAD

**Issue by marktopper** [gitscout/gitscout-feedback#155]
Would it be possible to have a option to disable notifications for hidden repositories?

**Comment by michael-lefebvre** [comment]
hi @marktopper, we published a new version today that must fit your request.

**Comment by marktopper** [comment]
I am already on the latest version `0.6.5`.

**Comment by michael-lefebvre** [comment]
hum, does the notifications appears in the list or are we talking about the popup?

**Comment by michael-lefebvre** [comment]
@marktopper ok, I get the problem 😓 we published a patch, let me know.

**Comment by marktopper** [comment]
Seems to work, thanks!
