### ISSUE TITLE
Gitscout email list should be opt-in

### ISSUE THREAD

**Issue by goodguyry** [gitscout/gitscout-feedback#156]
Connecting my Github account apparently signs me up for an email list.

While it's easy enough to unsubscribe, and the permissions do give Gitscout the ability to read my personal info, **email list auto-signup based on an email address you weren't explicitly provided is shady**.

**Comment by jeremybenaim** [comment]
@goodguyry we understand completely and are sorry if you feel spammed, that was definitely not our goal. :(
We'll make sure in the next release to let the user know and be able to opt-in and opt-out in their account preferences.

Thanks for your feedback!
