### ISSUE TITLE
People picker doesn't fetch more users as I scroll

### ISSUE THREAD

**Issue by willhou** [gitscout/gitscout-feedback#16]
My username starts with "w" but the end of the list is "c" :(

![Screen Shot 2016-07-18 at 11.14.21 AM](http://static.gitscout.com/dc69836f20cbc2dc118290741d30d5d0da77533823470caddabba16f9149a5a4.png)

**Comment by jeremybenaim** [comment]
hey @willhou, thanks for this one, you should be able to find yourself in the list with the new version ;)

To update, re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now"

Thanks! :)

**Comment by willhou** [comment]
It's working! Thanks!

![Screen Shot 2016-07-19 at 2.12.20 PM](http://static.gitscout.com/70c79142555053fbda07710865ffeb66ed0bb6b1452759f6a7a9fd0c2209df41.png)

**Comment by jeremybenaim** [comment]
![](http://media3.giphy.com/media/IxJMT1ugyBMdy/giphy.gif)

**Comment by willhou** [comment]
![so-much-win-starcraft-reaction](https://cloud.githubusercontent.com/assets/980331/16961526/e2487988-4dbb-11e6-9ab0-d2b9e8d111c8.gif)
