### ISSUE TITLE
Hide closed issues?

### ISSUE THREAD

**Issue by kernelp4nic** [gitscout/gitscout-feedback#160]
How do I hide closed issues?

**Comment by kernelp4nic** [comment]
Oh, I think this is kind of a dupe #158

**Comment by michael-lefebvre** [comment]
you can use _"smart filters"_ to hide repository's closed issues:

![open-issues](https://gitscout-dev.s3.amazonaws.com/23d2b0a7fee665cdde3c1ce59de69a7ce607bf28d5b80d92cd336dacd9ca8eeb.png)

**Comment by kernelp4nic** [comment]
oh! Thanks! just missed that sorry :)
