### ISSUE TITLE
Repo Switcher Hotkey

### ISSUE THREAD

**Issue by MartinWysi** [gitscout/gitscout-feedback#162]
Hi there, 

Love the app, just hoping you could add a hotkey e.g. "cmd+s" for the repo switcher search bar. 

(and/or the ability to set a custom hotkey for this)

Cheers.

**Comment by Adrien-Griveau** [comment]
@MartinWysi cmd +k is the shortcut for that.

**Comment by MartinWysi** [comment]
ah great! thanks for that, massive help!
