### ISSUE TITLE
Ability to export/download as csv the issues in a search result

### ISSUE THREAD

**Issue by rudimusmaximus** [gitscout/gitscout-feedback#168]
I'd love it if we could download search results (filtered issue list) in at least a csv.

Would provide a way to report on a subset of issues without giving access to my repo.
Like "extract results" or "download results" or "export results"

Anyone else like this?
Perhaps to include pull requests in future as well if they are added to the app.

**Comment by jeremybenaim** [comment]
Hi @rudimusmaximus thanks for you feedback 🙂 
I think this feature could be interesting but doesn't really fit in our roadmap right now
