### ISSUE TITLE
Reordering

### ISSUE THREAD

**Issue by welcometothesky** [gitscout/gitscout-feedback#17]
I'd love to reorder organizations and repos as I want. That would be really useful for 20+ repos org.

😘

**Comment by jeremybenaim** [comment]
Hey @welcometothesky thanks for the feedback!

This is definitely on our pipe (see #7 & #2) and should be available pretty soon 😉 

Bisous 😽

**Comment by jeremybenaim** [comment]
Hey @welcometothesky

This has been fixed in the new version (0.3.8) :)

To update, restart the app or go to Gitscout in your menubar then Preferences and "Check for updates"

Thanks ;)
