### ISSUE TITLE
Automatically update currently open issue on update

### ISSUE THREAD

**Issue by nijikokun** [gitscout/gitscout-feedback#172]
When you have an issue open in Gitscout and an update comes in currently you have to click another issue then click the issue you were looking at to see updates which clears that issue from being *unread*.

I'm a part of a vibrant community that comments frequently so I am finding myself running into this often.

**Comment by areskub** [comment]
Hey @nijikokun I completely agree. I already opened a ticket for that and mentioned @michael-lefebvre on our internal repo #395 so I'm closing this one
