### ISSUE TITLE
Announcements window doesn't close when clicking padding above

### ISSUE THREAD

**Issue by nijikokun** [gitscout/gitscout-feedback#173]
**Steps to reproduce:**

1. Select a repository
2. Open Announcements Window
3. Click area above announcements window (except announcements icon)
    
Image for reference:

![https://i.imgur.com/1u6zYMr.png](https://i.imgur.com/1u6zYMr.png)

**Result**

Announcement windows stays.

**Expected Result**

Announcement window disappears.

**Comment by areskub** [comment]
Hey @nijikokun thanks for the feedback, @michael-lefebvre already knows about this.

**Comment by michael-lefebvre** [comment]
Hi @nijikokun, fixed in [version 1.0.0-rc.1](https://github.com/gitscout/gitscout-feedback/issues/193) 😉
