### ISSUE TITLE
can't access some forked repos

### ISSUE THREAD

**Issue by olets** [gitscout/gitscout-feedback#174]
In particular, I can't access some repos forked from repos I don't have access to. They don't show in the Repositories list in the preferences, and I get the "invalid" popup when I try adding them manually.

It's _possible_ that the difference between these non-working repos and other, working repos forked from repos I don't have access to is the third-party access you point to in #79… maybe the source repo of the working ones have third party access enabled, but because I don't have access to them I don't know.

**Comment by michael-lefebvre** [comment]
Hi @olets, we don't display forked repositories because they don't have any "Issues" section.

**Comment by olets** [comment]
GitHub supports issues on forked repos, enabled on a per-repo basis in Settings > Features > Issues.

**Comment by michael-lefebvre** [comment]
Well spotted @olets ;) we keep a eye on this option but since it's not the default behavior of forked repos it might take a moment to take care of this case.
Thanks a lot for reporting it!

**Comment by olets** [comment]
👍  I haven't looked at the API, don't know if it's at trickier than usual. Fwiw [Trailer](https://github.com/ptsochantaris/trailer) manages it, so if it _is_ tricky that might be a helpful place to look. Thanks for a great app!
