### ISSUE TITLE
minor mistakes in "invalid repository access" modal

### ISSUE THREAD

**Issue by olets** [gitscout/gitscout-feedback#175]
- Double `•` bullets
- "Make sur"

![invalid repo modal](https://cloud.githubusercontent.com/assets/3282350/23758334/74056b94-04b7-11e7-9aa9-8a7349a58e77.png)

**Comment by michael-lefebvre** [comment]
Hi @olets, fixed in [version 1.0.0-rc.1](https://github.com/gitscout/gitscout-feedback/issues/193) 😉
