### ISSUE TITLE
Assignee/Author List

### ISSUE THREAD

**Issue by bgian** [gitscout/gitscout-feedback#18]
I'd like to see myself first in these lists since that's who I'm looking for most of the time.

![Screen Shot 2016-07-19 at 4.50.04 PM](http://static.gitscout.com/289d1f9e81c386267f71d2b94aec3fe935c79edaea09db28d02d042f77bd9ac2.png)

**Comment by jeremybenaim** [comment]
@bgian that makes total sense. Adding it in the next release :wink:

Thanks!

**Comment by jeremylv** [comment]
+1 on that request. Thank you.

**Comment by jeremybenaim** [comment]
Howdy @bgian @jeremylv

The newest version (0.3.8) has it :)

To update, restart the app or go to Gitscout in your menubar then Preferences and "Check for updates"

Thanks!
