### ISSUE TITLE
Here comes trouble! > Growl notification

### ISSUE THREAD

**Issue by stevenjohn** [gitscout/gitscout-feedback#182]
Just some feedback from a UX productivity point of view...

The purpose of good software is to make you feel GOOD - get things done, be more productive.

The language you bake inside your product defines the mental approach people with have. So having a really negative title to the Growl Notification:

**Here comes trouble!**
You have X things to work on...

You are instantly associating negative feelings towards your colleagues and the work you have to do. I find it so annoying I wanted to start looking at the codebase to try to tweak this message.

Given that Gitscount is ALL ABOUT making it easy to talk and deal with this 'trouble', I would love to see this changed to convey something more positive - so the notification might read:

**Your beloved colleagues need you!**
You have X things to work on...

**Calling all Superheroes!**
You have X things to work on...

OK, the last one is a bit cheesey - but you get the idea - don't associate 'trouble' with your product, its BAD psychology...

Cheers, Steve

**Comment by areskub** [comment]
Hi @stevenjohn 

Thanks for the feedback. I think we all agree on this. The copy for those dates back to the early prototypes and we never really took the time to change it.

I'll see that changes happen in one of the next builds. 👍

**Comment by stevenjohn** [comment]
Thanks for the update, and congratulations on creating something that with a few tweaks is a great product :)))

**Comment by michael-lefebvre** [comment]
Hi @stevenjohn, notification texts have been updated in [version 1.0.0-rc.1](https://github.com/gitscout/gitscout-feedback/issues/193) 😉
