### ISSUE TITLE
Close Issue

### ISSUE THREAD

**Issue by laurentdebuchy** [gitscout/gitscout-feedback#19]
Personnal thought icon for closing issues is not realy revelant
![Capture d’écran 2016-07-20 à 09.28.57](http://static.gitscout.com/daeb5e893f8ddb214b5aaf2aae3106ee2b7da4c40d0aff0e08dd0210535663d6.png)

**Comment by areskub** [comment]
And you're damn right about that.

**Comment by Victa** [comment]
I also feel that the UX is not that great (same for the "new comment" button)

* Icons are smalls
* Icons are not very clear and hard to notice at the bottom right when there is a bunch of comments in the issue
* Icons are hard to understand (maybe they need to have a label?)

Sorry if you already talk a lot about this UX and/or if you are happy with the UX of those buttons. Just wanted to share my though and I would be happy to do some explorations.

**Comment by jeremybenaim** [comment]
hey @laurentdebuchy we just released a new version (`0.4.0`) with new icons, and the close issue weird smiley is now a thing from the past 😉 

Please let us know what you think of the new icons, thanks! 😃
