### ISSUE TITLE
Error: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by shalaby** [gitscout/gitscout-feedback#192]
Error: TypeError: Failed to fetch
    at file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:6090:23
From previous event:
    at loop (file:///Applications/Gitscout.app/Contents/Resources/app.asar/workers.js:5926:31)

**Comment by michael-lefebvre** [comment]
hi @shalaby, please see #176 for more details.
