### ISSUE TITLE
Announcement is in the future!

### ISSUE THREAD

**Issue by entendu** [gitscout/gitscout-feedback#195]
Unless you have discovered how to read messages from the future, I think this timestamp is wrong!

![image](https://cloud.githubusercontent.com/assets/276273/26364172/42b4c6fe-3f98-11e7-98a4-0ba5bfd1a6ba.png)

**Comment by michael-lefebvre** [comment]
Damn, @entendu you found our next secret feature 😉 Bad timestamp in the source feed, fixed. Thanks
