### ISSUE TITLE
[1.0.0-rc3] Gitscout extremely slow

### ISSUE THREAD

**Issue by entendu** [gitscout/gitscout-feedback#198]
I'm looking at my unread notifications, and scrolling through the fairly small list (~400) is pretty choppy.

Also, making a comment on any of those issues is nearly impossible because of how slow it is.

**Comment by entendu** [comment]
This is much more pronounced when the issue list is long. This is me typing in a comment box with ~400 issues in the issue list:
![gs-type](https://user-images.githubusercontent.com/276273/27158708-3d7dc104-511d-11e7-8c35-b16361aa62b4.gif)

This is scrolling that list. Much more usable, but still annoying:
![gs-scroll](https://user-images.githubusercontent.com/276273/27158756-7c9e2630-511d-11e7-9c9b-d34f13f15930.gif)

**Comment by entendu** [comment]
I've had to stop using Gitscout for the time being because performance is just too bad for the number of notifications I have.

Good luck folks, I'll keep an eye on progress but for now I have to move on!

**Comment by fredsimard** [comment]
That's odd. I'm using a 2011 Macbook Pro, and it is as fast as would be expected. I do not have any of the issues you mention or demonstrated. I'm using macOS 10.12.5 btw.

**Comment by entendu** [comment]
How big is your notification list?

--
Domenic Santangelo
@entendu

**Comment by fredsimard** [comment]
Not 400. But if I look at Gitscout's own issues, (~200), it's just fine.
