### ISSUE TITLE
macOS 10.13 Rendering Issues

### ISSUE THREAD

**Issue by mikebronner** [gitscout/gitscout-feedback#199]
Please see the attached screenshot:
- There is a title bar that obstructs the upper portion of the window, pretty much preventing any meaningful work.
- Also, there is an artifact to the left of the app.

![screen shot 2017-06-15 at 10 12 10 am](https://user-images.githubusercontent.com/1791050/27193325-3eae6858-51b3-11e7-93f3-c05d0963e153.png)

I do realize that macOS 10.13 isn't out yet, just wanted to provide a heads up so it can be ready in time when macOS 10.13 is released. :) Thanks!

**Comment by fredsimard** [comment]
A similar issue exists on 10.12, when in fullscreen mode if you bring the mouse at the top edge of the screen.
![bug](http://static.gitscout.com/a01afdd34793912ad489a83aadd4d54013553efc186177864a4899ccdbf11aa7.png)

**Comment by pbadeer** [comment]
Note, this issue went away for me on the latest 10.13 update as of a few days ago. There were other programs (Spotify for example) that had similar title bar issues that were fixed in this update.

**Comment by mikebronner** [comment]
Agreed, this seems resolved now. :)

**Comment by fredsimard** [comment]
My issue i was having is on 10.12, not 10.13.

**Comment by mikebronner** [comment]
@fredsimard I reported it from 10.13 -- I havent used it in 10.12. Please open a separate issue for 10.12 if that is still persisting.
