### ISSUE TITLE
Collapsible organization

### ISSUE THREAD

**Issue by rno** [gitscout/gitscout-feedback#2]
I have quite a few organizations and repositories per organization, I'm not active on all the organisations not repositories.

Could you add collapse / expand on organization in the side panel?

**Comment by Adrien-Griveau** [comment]
thanks for your feedback. This is a good point we have other users having the same issue.

**Comment by Victa** [comment]
Also, any plan to `star` a respository? I have some many repository in my sidebar but I mostly go to 3 or 4 of them.

**Comment by jeremybenaim** [comment]
We definitely plan to let users manage their sidebar (hiding/showing org & repo) 

Should be coming pretty soon :wink:

**Comment by jeremybenaim** [comment]
Hello @rno

In the latest version (0.3.8) you can manage your sidebar repositories and organizations. Just head to your Preferences > Repositories

Thanks!
