### ISSUE TITLE
Changing issue title.

### ISSUE THREAD

**Issue by Kapulara** [gitscout/gitscout-feedback#23]
Right now i'm unable to change the titles of a issue. 

Probably not intended. Might be not too hard to implement.

:+1:

**Comment by Adrien-Griveau** [comment]
@kapulara you can edit the issue title by editing the first comment. 


![Screen Shot 2016-07-26 at 11.15.21 AM](http://static.gitscout.com/06e943307356384d869d4227f6530a8cbb4e4f54e1a29636888b1b71efabb519.png)

We should make this more easy. Thanks for your feedback.

**Comment by Kapulara** [comment]
Ooops missed it! Yeah a little icon that shows edit would be enough! :+1:

**Comment by briannhinton** [comment]
I would add a edit button, or icon next to the title.
