### ISSUE TITLE
Redo functionality for text!

### ISSUE THREAD

**Issue by Kapulara** [gitscout/gitscout-feedback#24]
Right now there is no feature to redo something that in the past you have undone.
(If that makes sense)

![Screen Shot 2016-07-26 at 17.07.56](http://static.gitscout.com/867af6bbe73d17e6803939c7ec42d679b6fb23333816a8aeefdc9899655b78e1.png)

Command + Shift + Z on text is what i'm talking about.

**Comment by jeremybenaim** [comment]
Hey @Kapulara 

`Command + Shift + Z` is now live in version 0.3.8  🎉 

To update, simply restart the app or go to Gitscout in your menubar then Preferences and "Check for updates"

Thanks! :)
