### ISSUE TITLE
Design: commenting button isn't not obvious

### ISSUE THREAD

**Issue by briannhinton** [gitscout/gitscout-feedback#26]
How to add a comment is not obvious. It took me a few misclicks ([+] clicked, clicking on containers) for me to try the little comment icon. 

Something more prominent would create a better UX. My personal recommendation would be to add a footer bar at the bottom of each issue with controls. (view issue on github, share issue, add comment, etc.)

**Comment by Adrien-Griveau** [comment]
@briannhinton I agree we have a lot of feedback about this now. I'm working on different versions.

I let you know when I have some new stuff for you. Thanks a lot for you feedbacks we really them. Don't hesitate to put more if you have some.

cheers,

**Comment by jeremybenaim** [comment]
howdy @briannhinton!

latest version (`0.4.0`) has a new design for the comment button (see #37)

would be super cool to have your feedback on this new design, thanks! :)

**Comment by briannhinton** [comment]
Much improved, and definitely more obvious. How about enter being tied to adding a comment as well?

**Comment by jeremybenaim** [comment]
You mean pressing the `Enter` key to open the new comment window?

**Comment by briannhinton** [comment]
Correct. It just seems intuitive. What do you think? Anyone else want to chime in?

**Comment by jeremybenaim** [comment]
Hm 🤔 `Enter` seems a bit too generic, but we're 100% for a keyboard shortcut to quickly access the comment window!

Any other suggestion maybe? (We can all agree `Cmd+C` is already taken 😅)

**Comment by briannhinton** [comment]
Alt+C?

**Comment by jeremybenaim** [comment]
Yea, could be...still doesnt feel _natural_ to me but we gonna try different combinations and pick up the best one

**Comment by jeremybenaim** [comment]
hey @briannhinton, how do you like our new design, the UX of commenting should be clearer now.
Any feedback? Thanks! 🙂
