### ISSUE TITLE
I can't make it to work after connecting it with Github

### ISSUE THREAD

**Issue by msilikale05** [gitscout/gitscout-feedback#270]
I have installed Gitscout in my Mac, but after I connected the app with Github account, I can't go back to Gitscout app from the link. All I get is "_**If this is not working after 5 seconds make sure Gitscout is installed or click here**_" But it never goes back to the app even after I click here but it is stack on the browser.

**Comment by dalholm** [comment]
@msilikale05 did you solve it? i'm having the same issue. :P

**Comment by dalholm** [comment]
@msilikale05 found it, related to https://github.com/gitscout/gitscout-feedback/issues/265

**Comment by dromerobarria** [comment]
Same problem and the issue #265 didnt solve it. So I cant use it.

**Comment by msilikale05** [comment]
Nope, that did not fix for me.
