### ISSUE TITLE
Search > highlight text

### ISSUE THREAD

**Issue by bgian** [gitscout/gitscout-feedback#28]
When I'm trying to highlight text in the search it's dragging the window instead.

**Comment by michael-lefebvre** [comment]
nice catch @bgian 😅

this will be fixed in the next release. 
Thanks for your feedback!

**Comment by jeremybenaim** [comment]
Hey @bgian

This has been fixed in the new version (0.3.8) :)

To update, restart the app or go to Gitscout in your menubar then Preferences and "Check for updates"

Thanks! :)
