### ISSUE TITLE
Global Notificaftions view

### ISSUE THREAD

**Issue by rno** [gitscout/gitscout-feedback#3]
I'm a big user and fan of the Notifications view in the Github website.

As I have quite a lot of organizations + repositories, having a global notifications view where I can see all the recent changes accross all the repositories would be really helpful for me.

Right now I have to go through my (gigantic) list of repositories and spot the blue dot.

Thank you a lot!

**Comment by jeremybenaim** [comment]
@rno the notifications panel is now live in version `0.5.0`. Would love to hear your feedback about it! 😊

**Comment by rno** [comment]
I love it!! Really! :fire:

Few small things though :angel:

I'm a heavy user of `Participating`, I always have a lot of issues to go through and starting with the ones I'm participating in is easier.

The other thing I use a lot is filtering on repository. It makes a lot of sense on github.com/notifications because it has a maximum visible issues per repository on this view. In GitScout it would make also sense I think because it would avoid me to scroll through the list of all the notifications to jump in a repository.

**Comment by bgian** [comment]
+1 for participating, this is usually what I check first thing :)

**Comment by michael-lefebvre** [comment]
Participating is available in [v0.6.0](https://github.com/gitscout/gitscout-feedback/issues/122) 🙂
We need your feedback to improve it 🙏
