### ISSUE TITLE
Commend and close should not be hidden by default

### ISSUE THREAD

**Issue by ForbesLindesay** [gitscout/gitscout-feedback#30]
When I'm looking at an issue, 90% of the time the action I'm going to take is to comment on the issue, so I shouldn't have to click a button to open the comment box.  The other 10% I'm going to be closing the issue.  I think GitHub's web interface does a much better job of both of these.

**Comment by jeremybenaim** [comment]
@ForbesLindesay thanks a lot for sharing your thoughts on that :)

The first version of Gitscout had a comment box at the bottom but we removed it to make more room for the conversation, but you're definitely right and we're currently exploring ways to put it back there

maybe @Adrien-Griveau can give you a sneak peek of what it might look like in a few weeks ;)

**Comment by Adrien-Griveau** [comment]
@ForbesLindesay Here what we are working on now. Could that help you commenting? 



![Screen Shot 2016-08-04 at 10.59.10 AM](http://static.gitscout.com/f9bf4f8365c5e7f9dcc63dc53d4a5e5d4689069cd43ee6b9d57b15a7c8f1763d.png)

Thanks for you feedbacks.

**Comment by lucasmarcelli** [comment]
Typo: Label -> Labelled

**Comment by Adrien-Griveau** [comment]
@lucasmarcelli 
![images](http://static.gitscout.com/3a58902ecde030a16be9bd74c6623e062a11441d7bd38ab4c1bb87f478668c01.jpeg)

**Comment by ForbesLindesay** [comment]
Thanks, this looks like a huge improvement.

**Comment by jeremybenaim** [comment]
Hello @ForbesLindesay, we just released a new design in the latest version which you should hopefully find clearer and smarter. ☺️ 
Would love to hear your feedback on it, thanks 😉
