### ISSUE TITLE
I need to be able to collapse orgs and search for repos

### ISSUE THREAD

**Issue by ForbesLindesay** [gitscout/gitscout-feedback#31]
I have somewhere between 400 and 600 repositories.  Scrolling through the entire list is really painful.  It would help if I could:
1. Collapse organisations (and have them collapsed by default).
2. Search for repos by name.

**Comment by jeremybenaim** [comment]
hey @ForbesLindesay, thanks for bringing that up! :)

We already addressed this issue (sort of) by letting the user manage their repos in the Preferences, in the Repositories tab.
There you'll be able to select the repositories and organisations you want to display in the sidebar.

That might not exactly be what you suggested but definitely can help finding your way thru your 600+ repos :D

We're working on some designs to make the sidebar smarter and more effective, will definitely keep you posted on that!

**Comment by ForbesLindesay** [comment]
The problem is that I don't have 600+ dormant repos that I no longer maintain.  I have 600+ repos, most of which are active.  What I mostly wan to do is be able to see all of the issues for one org in a single list, and only split out by project for projects that are very active.

**Comment by jeremybenaim** [comment]
Thanks for the precisions

Actually, solving #32 would be a good way to solve this ;)
