### ISSUE TITLE
Allow use of up/down keys to browse issues

### ISSUE THREAD

**Issue by quentez** [gitscout/gitscout-feedback#33]
When browsing the issues list, it would be convenient to move to the previous/next with the keyboard (up/down).

**Comment by jeremybenaim** [comment]
hey @quentez thanks for your feedback, that's clearly on our roadmap (see #14) 

will keep you posted once it is shipped :)

**Comment by jeremybenaim** [comment]
@quentez we just shipped a new version (`0.4.0`) with this cool lil' feature and more (see #37) :blush:
