### ISSUE TITLE
Add to to-do if assigned to issue

### ISSUE THREAD

**Issue by sparkdevelopment** [gitscout/gitscout-feedback#36]
It would be great if there was an option to automatically add issues to our to-do list if they're assigned to us.

And possibly the reverse if unassigned?

Or at least display them differently in the issue list so they're easier to identify (this would be useful for closed issues)

**Comment by sparkdevelopment** [comment]
That's nice - so does that replace the To Do star button and appear above your repos?

**Comment by Adrien-Griveau** [comment]
No, I think todo is going to be rename as saved. So you will be able to add whatever issues into this. This is not final design we are just trying new things.

**Comment by jeremybenaim** [comment]
@sparkdevelopment the "Saved issues" feature is now live. Would love to hear your feedback on it!
