### ISSUE TITLE
Ability to paste & upload an image to a comment

### ISSUE THREAD

**Issue by gavinanthony** [gitscout/gitscout-feedback#39]
Similar to the Github UI where I can paste a screenshot into a comment of an issue and it automatically uploads/formats it

**Comment by gavinanthony** [comment]
Also, I noticed a typo in the readme: "Visit chanlog for latest update."

**Comment by michael-lefebvre** [comment]
Hey @gavinanthony, thanks for your feedback and proof writing 😅. 

I'm not sure to understand your request about image upload. You can attach image/file to comment by drag and drop or using 📎 button. Can you give us more details please ?

**Comment by gavinanthony** [comment]
In the Github UI, you can paste an image from your clipboard directly into the comment like this: 
<img width="780" alt="ability_to_paste___upload_an_image_to_a_comment_ _issue__39_ _gitscout_gitscout-feedback" src="https://cloud.githubusercontent.com/assets/392797/18113488/436ae558-6efe-11e6-83ca-8f98f7c7b83d.png">

Would be extremely handy! Most of the images I attach to comments all come from my clipboard.

**Comment by michael-lefebvre** [comment]
Hey @gavinanthony, thanks for your explanations 👍.

We added this feature to the latest update 🙂

**Comment by jeremybenaim** [comment]
![](http://66.media.tumblr.com/d97a5b6149d1ceaae40bc0264136a434/tumblr_njsi0bJYeI1skwgg1o6_400.gif)

**Comment by Adrien-Griveau** [comment]
![gitscout-image-from-clipboard-2](http://static.gitscout.com/8fc9eb202a10b63f2bd389c715629887b8b644eb3e4c8a879872f7aa59568a14.png)

**Comment by Adrien-Griveau** [comment]
![giphy](http://static.gitscout.com/1f76e1fc3c27854e19d48470b70e9ccca11c9b508405366f898c64f0def2d789.gif)

**Comment by gavinanthony** [comment]
![gitscout-image-from-clipboard-1](https://media.giphy.com/media/sx5RIqRIx0qZ2/giphy.gif)
