### ISSUE TITLE
Wrong timestamp

### ISSUE THREAD

**Issue by rno** [gitscout/gitscout-feedback#4]
The timestamp does not reflect the last change properly:

Gitscout | Github
------------ | -------------
<img src="http://static.gitscout.com/fee53693c11d1962ff59ef5379ea5389bcb19a2e01f7d3052658c2e8ad7b75dd.png" width=300 /> | <img src="http://static.gitscout.com/4d8ee7f47e78b76c46a19b7c78048eccc6b27000ca9a1d40bacad30048aacd24.png" width=300 />

**Comment by jeremybenaim** [comment]
Fixed in the upcoming release! :)

**Comment by jeremybenaim** [comment]
And, its live! ❤️ 

To get the latest version, re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now"

Thanks :)
