### ISSUE TITLE
UX: Ability to comment from the main window

### ISSUE THREAD

**Issue by julien-c** [gitscout/gitscout-feedback#40]
For comments I think it would be simpler to be able to just post them from the main window (no popups)

Thoughts?

![Capture d’écran 2016-09-16 à 13.51.53](http://static.gitscout.com/629c73e5d4219c4213876fd64d63fa63a64402e634bfc834f47889c3ad9a335e.png)

**Comment by jeremybenaim** [comment]
Hey @julien-c, thanks for your feedback! 

This is on our roadmap for an upcoming major release and it should look like that : https://github.com/gitscout/gitscout-feedback/issues/30#issuecomment-237579951 

Would love to hear your thoughts about it :)

**Comment by julien-c** [comment]
Loving it

**Comment by jeremybenaim** [comment]
![](http://i.giphy.com/UxJjs7Kah20OA.gif)
