### ISSUE TITLE
Feature: add emoji reaction on issues

### ISSUE THREAD

**Issue by julien-c** [gitscout/gitscout-feedback#41]
If Github is exposing it in their API this is a must have! Keeps the conversation cleaner too

cc @Adrien-Griveau

![Capture d’écran 2016-09-16 à 13.56.23](http://static.gitscout.com/4131a448c2e62426a60a6c7f7ec97d3e7517c663d2b1f2d5b624094f5099143b.png)

**Comment by jeremybenaim** [comment]
Available on the latest version!  😊  More details here #42
