### ISSUE TITLE
Closing popin

### ISSUE THREAD

**Issue by foOg** [gitscout/gitscout-feedback#43]
Would be good to be able to close the new issue popin using ESC or when click outside.
The trash is not obvious.

![Capture d’écran 2016-11-16 à 12.27.48](http://static.gitscout.com/abca4c7cd9b5575f9e42592acdd00fb413a8c57ea86da90daa1f8575d8464c1c.png)

**Comment by jeremybenaim** [comment]
Roger that @foOg!

We're going to change this in the next release!

Thanks for reporting it :)

**Comment by foOg** [comment]
Just saw it, thanks!

**Comment by michael-lefebvre** [comment]
we gonna spread this pattern across the app, thanks @foOg
