### ISSUE TITLE
Sticky headers for organizations

### ISSUE THREAD

**Issue by rno** [gitscout/gitscout-feedback#44]
rno's repository is visible | rno's repository is hidden
------------ | -------------
![Screenshot 2016-11-17 10.17.07](http://static.gitscout.com/4bf96ec42cfa082efd85b229f802c55721e5bf1262db47639f5c0fa9c2462f76.png) | ![Screenshot 2016-11-17 10.18.39](http://static.gitscout.com/ffe0799c63a951f9f8949a154be12eff70634bbdd4054ed3bff77732b4b7f1d2.png)

It would be nice to have a sticky header for organizations :-)

**Comment by michael-lefebvre** [comment]
@rno you mean in the sidebar?

**Comment by rno** [comment]
Yes @michael-lefebvre
