### ISSUE TITLE
Reorder repos on the left column (drag and drop)

### ISSUE THREAD

**Issue by oursroux** [gitscout/gitscout-feedback#46]

**Comment by jeremybenaim** [comment]
@oursroux thanks for that one, that's definitely something we would consider in an upcoming release 😊

**Comment by michael-lefebvre** [comment]
@oursroux feature available in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂 You can reorder your Organizations from your settings. Soon you will be able to reorder repositories too.
