### ISSUE TITLE
image links are broken

### ISSUE THREAD

**Issue by selfagency** [gitscout/gitscout-feedback#48]
image files uploaded through gitscout to the gitscout cloud appear as broken image links

**Comment by jeremybenaim** [comment]
@selfagency that's odd, I just uploaded this one and everything seems ok:

![Screen Shot 2016-11-30 at 10.53.01](http://static.gitscout.com/10c935311c7e5f7edb60747f981aff8557567637ad769f0b0c8eddb136e81169.png)

Maybe you experienced a small delay in the upload which might appears as a broken image the first time you see it but should be ok the second time. 

Can you try again and let me know? Thanks!

**Comment by selfagency** [comment]
![12234946_864789083636052_8353137535176917578_n](http://static.gitscout.com/ebbe5bdfa82aeb592acdac244e9c6f29b9b0eecb760d649478438f2710059bd4.jpg)

**Comment by selfagency** [comment]
yes, it appears if i leave the ticket and come back to it, then it works. why not automatically refresh after an image upload?

**Comment by selfagency** [comment]
this works now
