### ISSUE TITLE
Can't find myself in the list of the assignees

### ISSUE THREAD

**Issue by Victa** [gitscout/gitscout-feedback#5]
Hello,

I can't find my name in the list of the assignees.

I feel like I am missing a lof of people too because it looks like the names are ordered from A to Z and the list stops to someone named `D...`.

(there is a **lot** of people in that repository - maybe a pagination issue?)

Gitscout | Github
--- | --- 
![Screen Shot 2016-07-13 at 16.40.13](http://static.gitscout.com/4ee1c50dbb675875a067e25db8ce2fec5ee8f56466f506521db32f8cfbabff10.png) | ![screen shot 2016-07-13 at 16 49 18](https://cloud.githubusercontent.com/assets/594365/16819302/cd542014-4919-11e6-81b1-ae000882e58b.png)

**Comment by Adrien-Griveau** [comment]
This is how the assign display on github 

![Screen Shot 2016-07-13 at 4.45.19 PM](http://static.gitscout.com/f5280953772278a2f798581f7526322411772a3546016cf220fc9633a77d6df4.png)

**Comment by Adrien-Griveau** [comment]
thanks

**Comment by Adrien-Griveau** [comment]
thanks

**Comment by jeremybenaim** [comment]
@Victa thanks again for reporting that one, fixed on the newest version!

Just re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now" and you'll be all set
