### ISSUE TITLE
Hide meta options based on permission

### ISSUE THREAD

**Issue by bgian** [gitscout/gitscout-feedback#50]
I can see options that I don't have permissions to change (in this case the `gitscout-feedback` repo) and won't actually carry over to GitHub.

![Screen Shot 2016-11-29 at 1.24.40 PM](http://static.gitscout.com/13ab66438ce57b9e760b8d18b2319aeb23883691f8261f6459b0a3d2a44e09d1.png)

**Comment by michael-lefebvre** [comment]
hi @bgian, I can't reproduce this case in current release, is it the same for you? thanks 🙂

**Comment by antoinerey** [comment]
@michael-lefebvre Yes, it's still there in 0.5.4. 

It appears when you're making a new issue. For existing issue though, it does not show up.

**Comment by michael-lefebvre** [comment]
ouch, I just understood that you were talking about the composer, not ticket header 😓

fix will be available in upcoming release, thanks @bgian and @antoinerey 👍

**Comment by michael-lefebvre** [comment]
Available on the latest version! 😊
