### ISSUE TITLE
feature request: mute alerts

### ISSUE THREAD

**Issue by selfagency** [gitscout/gitscout-feedback#52]
would love to see a feature where you can mute alerts for an individual repo or user/organization by clicking the gear next to the item in the sidebar and selecting mute. if you select a whole user/org, you should still be able to unmute individual repos within that account.

**Comment by michael-lefebvre** [comment]
hi @selfagency, your dream come true! 
You can mute a repository from the sidebar on the latest version! 😊 
More details here #90
