### ISSUE TITLE
feature request: support for pull requests

### ISSUE THREAD

**Issue by selfagency** [gitscout/gitscout-feedback#54]
it would be great if you could optionally include pull requests among your issues so you can track discussions on those PRs

**Comment by jeremybenaim** [comment]
Hey @selfagency, thanks for your feedback! this is actually one of the most anticipated item on our roadmap. 

We'll sure let you know when it is available 🙂

**Comment by bobdenotter** [comment]
Gitscout is a great tool, but a feature like this would make it truly invaluable for me. I spend a _lot_ of time on this screen, monitoring my open PR's across a number of repositories: 

https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Abolt+user%3Abobdenotter+

If I could do that with Gitscout, I'd be a happy camper. :-)

**Comment by oarrabi** [comment]
👍  Would love to see this feature too!

**Comment by z3t0** [comment]
Is this still being considered?

**Comment by matthewdias** [comment]
any reason you closed this @selfagency ?

**Comment by selfagency** [comment]
cleaning up my open issues. i made the request over a year ago and it's gone nowhere. i figured you'd either put it on the roadmap already or it wasn't happening.

**Comment by selfagency** [comment]
closing this because it's 5 years old, this project is defunct, and i want to clean up my issues tab
