### ISSUE TITLE
feature request: refresh button & hotkey

### ISSUE THREAD

**Issue by selfagency** [gitscout/gitscout-feedback#56]
right now the only way i can refresh a ticket is by clicking off to another ticket and clicking back on. it would be preferable if i could hit the standard refresh hotkey, cmd-R (instead of it going to notifications) or click a refresh button in the toolbar. tickets should also get auto-refreshed when a push notification comes in that it's been updated.

**Comment by michael-lefebvre** [comment]
@selfagency, really good idea, so we did it 😉 

`⌘+R` is available in [v0.6.0](https://github.com/gitscout/gitscout-feedback/issues/122) to refresh ticket and issues views.

thanks again for your great feedbacks 🤗

**Comment by selfagency** [comment]
this function currently crashes the app
