### ISSUE TITLE
Just letting you know a submitted a PR to cask for this

### ISSUE THREAD

**Issue by thibmaek** [gitscout/gitscout-feedback#59]
https://github.com/caskroom/homebrew-cask/pull/27525

**Comment by jeremybenaim** [comment]
oh wow @thibmaek this is awesome! Thanks!! 😍

**Comment by thibmaek** [comment]
No problem, seems as it is already merged and I'm now using it installed from cask.
If you guys would change the url for the download give me a heads up and I'll edit the PR (or you guys can do it :) )

**Comment by jeremybenaim** [comment]
Will definitely do! 😊

Massive thanks! That's really cool! 😎

![jawesome](http://i.giphy.com/YmiL1QKb89fPi.gif)

**Comment by pamo** [comment]
Happy you did this @thibmaek! Would be cool to see it in the download instructions for anyone else wondering if it's available with homebrew cask.

**Comment by thibmaek** [comment]
@pamo Sure, I'd love to add that in. Don't see the repo anywhere though.

**Comment by pamo** [comment]
Yup same. I'd put in a pull request myself but...
