### ISSUE TITLE
Posting a comment while I'm in "Preview" mode

### ISSUE THREAD

**Issue by Victa** [gitscout/gitscout-feedback#6]
Hello,

It looks like I can't post a comment when I'm in `preview` mode.

That would be great to be able to (or make the `submit` button looks disabled).

Thanks!

**Comment by jeremybenaim** [comment]
Yup, we catched that one too and it's already fixed, ready to ship in the upcoming release :)

**Comment by jeremybenaim** [comment]
@Victa With the latest version this will be over! :)

To get the latest version, re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now"

Thanks, and keep the feedback coming ;)
