### ISSUE TITLE
Authentication in browser

### ISSUE THREAD

**Issue by bdougherty** [gitscout/gitscout-feedback#63]
I'd like to be able to authenticate in the browser so I can fill in with my password manager and so I don't expose my password to the app.

**Comment by dhritzkiv** [comment]
Agreed. This is a blocker for me to use the app.

**Comment by jeremybenaim** [comment]
@bdougherty @dhritzkiv thanks for reporting this one, we're going to see what we can do to fix this as soon as possible

**Comment by chasenlehara** [comment]
To add on to this: when I was authenticating the app, I clicked on one of the links on the page, but couldn’t go back to the auth page, so I had to start over again.

**Comment by michael-lefebvre** [comment]
@bdougherty, @dhritzkiv and @chasenlehara, done!  🛠

Next release will process authentication in the browser. 
Thanks

**Comment by michael-lefebvre** [comment]
Available on the latest version! 😊 More details here #90
