### ISSUE TITLE
Purpose of Gitscout Account

### ISSUE THREAD

**Issue by tobihagemann** [gitscout/gitscout-feedback#66]
Hi there! Just wanted to ask what the purpose of the Gitscout account is. I didn't proceed because I don't understand why an additional account is needed. Shouldn't the authentication through GitHub be sufficient?

**Comment by areskub** [comment]
Hi!

We use accounts mostly for storing user preference (like what repos you hide/show), and to keep your data across desktops. The purpose is for you to have the same experience everywhere and not having to configure everything all the time.

In the long term, we'll also use that for project management. But that's not before a little while

**Comment by tobihagemann** [comment]
Thanks! I can understand that it might also be a strategic way for marketing etc., but looking from a functional perspective... can't this be optional?

**Comment by Adrien-Griveau** [comment]
@tobihagemann We need this because you have an account with Gitscout. You're saved issue and your repositories organizations is linked to your account, those informations are saved on your GitScout account.

We don't plan to configure this as optional for now.

**Comment by tobihagemann** [comment]
I understand that you need this right now, but these data can be stored locally as well. There is no technical necessity for it being linked to a secondary account other than "cloud synchronization" (available on all devices). But I understand that you don't want to make it optional for the sake of simplicity.

Thanks for the explanation! :smile:
