### ISSUE TITLE
2FA doesn't work

### ISSUE THREAD

**Issue by soderlind** [gitscout/gitscout-feedback#69]
I can't log in using 2FA.

**Comment by ghost1227** [comment]
For what it's worth, I just logged in with 2FA without any issues.

**Comment by aleccool213** [comment]
Same here

**Comment by soderlind** [comment]
hmm .. I had to use my recovery code to log on.

**Comment by jeremybenaim** [comment]
@soderlind should I close this one?

**Comment by apertureless** [comment]
Don't want to hijack the issue, but I encountered a similar issue. 

2FA Login with a security key, seems not to work.  I have a yubi key set up with my gh account. 
But every time I click login and enter my user + pw, the 2FA screen appears with "enter your security key and press the button", bit instantly there is a "oops an error occured" or smth like this.

Workaround was to use the software based token. But... it's still a bug :)

**Comment by jeremybenaim** [comment]
thanks @apertureless. definitely gonna investigate on how to make 2FA login more stable!

**Comment by hardcoded-dev** [comment]
Similar Issues here: Can't login with OTP app. Tried to create a new token: It always says wrong PIN.
Tried 3 Apps: Android Token, FreeOTP and OneTimePad, all scan the QR code and are generating tokens without problems. At least Android Token already worked in the past.

**Comment by michael-lefebvre** [comment]
Hi @soderlind, next release will process authentication in the browser. I'm think this will solve the problem. #63

**Comment by michael-lefebvre** [comment]
Browser auth on the latest version! 😊 More details here #90
