### ISSUE TITLE
Collapse sidebar items

### ISSUE THREAD

**Issue by arisawyers** [gitscout/gitscout-feedback#7]
Being able to hide the list of repos would be useful, especially for users who are in many organizations.

![Screen Shot 2016-07-13 at 4.58.01 PM](http://static.gitscout.com/aa83d72dc065ab96b065e47abdabae6d3c841becbca60dcd06fa763d42913ae3.png)

![Screen Shot 2016-07-13 at 4.58.09 PM](http://static.gitscout.com/b9a0789010fe4b874114316f35c5c682f3da429b6a4f14cf5d96a0c67c755bc4.png)

**Comment by jeremybenaim** [comment]
(sorry, wrong manipulation)

Yep, definitely! 
See #2

**Comment by jeremybenaim** [comment]
Hey @arisawyers

Grab the new version (0.3.8) and you'll be able to manage your sidebar repositories and organizations. Just head to your Preferences > Repositories

;)
