### ISSUE TITLE
Unable to filter milestones with dots in name

### ISSUE THREAD

**Issue by mikemclin** [gitscout/gitscout-feedback#73]
Our milestone names often are semver release names.  I was unable to filter by my `v1.0.0` milestone.  It appears to terminate the milestone name at the dot.

<img width="384" alt="screen shot 2016-12-10 at 4 24 14 pm" src="https://cloud.githubusercontent.com/assets/1570155/21076280/72789074-bef5-11e6-954b-ce0042cfadc1.png">

**Comment by michael-lefebvre** [comment]
ouch! good catch @mikemclin 😱 This will be fixed ASAP and available in next week release. Thanks for the feedback 👍

Until next release, if you need to filter issues with this milestone, you can wrap it with quotes (sounds lame, I know, but it works 🛠)

![Capture d’écran 2016-12-10 à 22.52.17](https://gitscout-dev.s3.amazonaws.com/4186bfc2ea351fc69c3e471b06376a7655fa0e19f4211cd73a028a3ef444e500.png)

**Comment by mikemclin** [comment]
Thanks for the work-a-round tip and the fast response

**Comment by michael-lefebvre** [comment]
@mikemclin fixed on the latest version! 😊 More details here #90
