### ISSUE TITLE
Don't auto-subscribe us to gitscout issues plz

### ISSUE THREAD

**Issue by PimDeWitte** [gitscout/gitscout-feedback#74]
Wasn't by my computer, unsubscribing on mobile didn't work, had 2 days of spam on my phone because I was auto-subscribed to the feedback channel somehow. Love the product, please fix it!

**Comment by michael-lefebvre** [comment]
hi @PimDeWitte, sorry for the inconvenience, we removed the "Auto Follow" option yesterday (see #62). For accounts created before this date you need to manually "unsubscribe". 

Once again sorry for the "spam", it wasn't the goal. 😔
