### ISSUE TITLE
'Close Window' Behavior

### ISSUE THREAD

**Issue by ROUND** [gitscout/gitscout-feedback#75]
When clicking the 'x' button in the top left, the entire application (process) closes instead of just closing the window. This is counter to expected behavior for Mac OS apps.

**Comment by areskub** [comment]
Agreed. Can we do something about that @michael-lefebvre ? Red traffic light should mimic ⌘W

**Comment by cjdowner** [comment]
:+1: this is driving me mad.

**Comment by michael-lefebvre** [comment]
@ROUND and @cjdowner, fixed in [0.5.8](https://github.com/gitscout/gitscout-feedback/blob/master/CHANGELOG.md#058---212017), thanks reporting this 🙏

**Comment by ROUND** [comment]
I can confirm!
