### ISSUE TITLE
Can't Hide GitScout window

### ISSUE THREAD

**Issue by maxvoltar** [gitscout/gitscout-feedback#8]
`CMD + H` doesn't work, "Hide GitScout" item isn't in the "GitScout" item of the menu bar.

**Comment by Adrien-Griveau** [comment]
Thanks for your feedback :) We're looking forward to fix it soon.

**Comment by jeremybenaim** [comment]
@maxvoltar fixed in a fresh new release :)

Just re-open the app or head to GitScout > Preferences in the menu bar and "Check for update now"

And thanks again, keep feedback-ing! 👍

**Comment by tomkowaty** [comment]
test - sorry
