### ISSUE TITLE
Impossible to use the mouse to select some text from the search bar

### ISSUE THREAD

**Issue by antoinerey** [gitscout/gitscout-feedback#80]
**Step to reproduce**

1. Type some text in the search bar (not pre-defined tag)
2. Try to select this text with your mouse

When trying to select some text from the search bar, it moves the window instead. In order to actually select the text, we need to use the keyboard. Dunno if this is a bug, but I find it pretty annoying. ;)

**Comment by michael-lefebvre** [comment]
hi @antoinerey,

thanks for your feedback, this will be fixed in next release 😅

**Comment by michael-lefebvre** [comment]
@antoinerey This took longer than I thought but it's finally fixed in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂
