### ISSUE TITLE
Why are so many permissions requested?

### ISSUE THREAD

**Issue by kdambekalns** [gitscout/gitscout-feedback#81]
I understand the application needs read access to some data and of course write access to issues. But why does it need **full access** to my user data, code, wikis, settings, webhooks and deploy keys?

This seems overkill.

**Comment by michael-lefebvre** [comment]
Hi @kdambekalns, thanks for your feedback.

We totally understand your concerns about permissions and we try reduce scope. I'm pretty optimistic that we will be able to remove the "user full access" in next release.

**Comment by kdambekalns** [comment]
Good to hear!

As far as code and wiki access goes, can that be stripped down a bit as well? I get issues and PRs (they are supposed to be managed after all) but why code and wikis? Or does GutHub not allow more fine-grained control?

**Comment by michael-lefebvre** [comment]
Hi @kdambekalns, we remove `user` scope on the latest version! 😊 
More details in #90
