### ISSUE TITLE
The `spell check` setting in not saved when quitting the application

### ISSUE THREAD

**Issue by antoinerey** [gitscout/gitscout-feedback#89]
**Steps to reproduce**

1. Start the application
1. Uncheck the `spell check` setting
1. Restart the application
1. Now, the `spell check` setting is checked again

**Comment by michael-lefebvre** [comment]
@antoinerey thanks for your feedback, it will be fix in upcoming release

**Comment by michael-lefebvre** [comment]
Fixed on the latest version! 😊 More details here #90
