### ISSUE TITLE
Account creation doesn't work

### ISSUE THREAD

**Issue by pjan** [gitscout/gitscout-feedback#91]
Stuck on the first screen requesting `user name`, `company` and `email`, it doesn't do anything upon pressing the `[ Create your account ]` button.

Latest version (0.5.6), downloaded 5 minutes ago.

**Comment by jeremybenaim** [comment]
@pjan thanks for reporting it! we're going to fix this asap!

**Comment by jeremybenaim** [comment]
@pjan we just released a [new version (0.5.7)](https://gitscout.com/marshmallows) to fix it! thanks a ton for reporting it! 🙏
