### ISSUE TITLE
Collapse organization

### ISSUE THREAD

**Issue by slimiles** [gitscout/gitscout-feedback#94]
It would be really nice to collapse the organizations, because I have a lot repositories and the sidebar is getting messy. 🙃

**Comment by Adrien-Griveau** [comment]
@slimiles we are working on something like that, what do you think?

thx for your feedbacks.

![Screen Shot 2016-12-19 at 11.44.32 AM](http://static.gitscout.com/cfb37f67d2b553fa5ad688f46e7b5457431abd84157395ec4f4a260045d3a2a1.png)

**Comment by slimiles** [comment]
Yeah, that looks nice. 👍🏼  Maybe a search would be nice too (for fast filtering).

**Comment by Adrien-Griveau** [comment]
@slimiles you can use the quick filter at the bottom of the sidebar for quick repo access. ![Screen Shot 2016-12-19 at 11.23.11 PM](http://static.gitscout.com/bfc72d0fac20ab2b21bfbc1a05d163118988c47ce3ef8ca82fd2596d2cd66e4d.png)
