### ISSUE TITLE
Notifications > Mark as read

### ISSUE THREAD

**Issue by bgian** [gitscout/gitscout-feedback#95]
I wish once I was done checking an issue, there was a way to clear it from my notifications list.

**Comment by areskub** [comment]
Like a... Swipe to mark as read? https://media.giphy.com/media/5p2wQFyu8GsFO/giphy.gif

Please say yes @michael-lefebvre 🙏

**Comment by bgian** [comment]
@michael-lefebvre ❤️

**Comment by michael-lefebvre** [comment]
@bgian mark as read on swipe available in [v0.6.2](https://github.com/gitscout/gitscout-feedback/issues/140) 🙂

**Comment by bgian** [comment]
@michael-lefebvre 💯 💯 💯

**Comment by michael-lefebvre** [comment]
Quick actions such as _"mark as read"_ or _"unsave issue"_ collapse list's item 🎉
