### ISSUE TITLE
Add link to this repo to give feedback/report bugs

### ISSUE THREAD

**Issue by maxvoltar** [gitscout/gitscout-feedback#96]
Had to go to the website to find this repo :)

**Comment by michael-lefebvre** [comment]
Hi @maxvoltar, this repository is automatically added to your list when you create your account. You can find it in your sidebar or by using `⌘+k`. 

By the way, we're looking to add a button to UI to help users to share their feedbacks/bug reports. Any suggestions? 🙂

**Comment by maxvoltar** [comment]
![image](https://cloud.githubusercontent.com/assets/125779/21506833/1ad730c4-cc28-11e6-98f7-558ad54dc8f4.png)

Here's where we put it in Abstract. I think it's a place people expect to find links to give feedback.

**Comment by michael-lefebvre** [comment]
@maxvoltar we followed your advice and add the same "Help" menu than Abstract 😉

**Comment by maxvoltar** [comment]
❤

On Jan 24, 2017 at 10:10, Michael Lefebvre <notifications@github.com> wrote:


@maxvoltar <https://github.com/maxvoltar> we followed your advice and add
the same "Help" menu than Abstract 😉

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitscout/gitscout-feedback/issues/96#issuecomment-274886836>,
or mute the thread
